// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:bd8d8f2f-6334-4597-ae53-39255cd7f924",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_BfE4VN1Ii",
    "aws_user_pools_web_client_id": "3ivmo2isgs47hiirkbedpq2kkj",
    "aws_appsync_graphqlEndpoint": "https://koqyycnicfegnefmasnb4x6jvq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-olfyrstsujhftpwh3ahohzlive"
};


export default awsmobile;
